# Generated by Django 2.2.16 on 2020-10-12 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_product_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cart',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Корзина'),
        ),
    ]
